config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'messages', to:'chatroom#messages'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages
  has_many :users
end

app/models/message.rb
class Message < ApplicationRecord
  has_one :conversations
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence:true, length: { minimum: 3, maximum: 20 }, uniqueness: { case_sensitive: false }
  has_many :conversations
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  def home
  end

  def messages
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create 
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Log in was successful"
      redirect_to user
    else
      # flash[:notice] persists for 1 full http request, render does not call a request it simply displays the new page, must use flash.now
      flash.now[:alert] = "Email or password was incorrect"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path, status: :see_other
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show,:edit,:update, :destroy]
  # before_action :require_user, only: [:edit, :update]
  # before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    # @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    # @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    # @user = User.new
  end

  def edit
  end

  def update
    # if @user.update(user_params)
    #   flash[:notice] = "Your account information was successfully updated"
    #   redirect_to @user
    # else
    #   render 'edit'
    # end
  end

  def create
    # @user = User.new(user_params)
    # if @user.save
    #   session[:user_id] = @user.id
    #   flash[:notice] = "Welcome to Alpha Blog #{@user.username}! You have succesffully signed up"
    #   redirect_to articles_path
    # else
    #   render 'new'
    # end
  end

  def destroy
    # @user.destroy
    # session[:user_id] = nil if @user == current_user
    # flash[:notice] = "Account and all associated articles successfully deleted"
    # redirect_to root_path
  end


  # private
  # def user_params
  #   params.require(:user).permit(:username, :email, :password)
  # end

  # def set_user
  #   @user = User.find(params[:id])
  # end

  # def require_same_user
  #   if (current_user != @user && !current_user.admin?)
  #     flash[:alert] = "You can only edit or delete your own account"
  #     redirect_to @user
  #   end
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/messages.html.erb
<h2>Messages</h2>

<%= react_component("ChatApp") %>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="navbar-content">
    <div class="navbar-content-logo">
      <i class="fa-regular fa-message"></i>
       <%= link_to "MessageMe", root_path, class: "navbar-content-logo-text" %>
    </div>
    <div class="navbar-content-links">
      <ul>
        <%= link_to 'Messages', messages_path, class:"nav-link #{request.path == "/messages" && 'active'}" %>
        <%= link_to 'Log in', root_path, class:"nav-link"%>
        <%= link_to 'Sign up', root_path, class:"nav-link"%>
        <%= link_to 'Logout', root_path, class:"nav-link", data: { "turbo-method": :delete }%>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>